data_files:
  structure: simulation_data/Acetaminophen_orthorhombic.cif
  
  # prepared euler_angles, dps, and targets
  dp_images_path_train: ${hydra:runtime.cwd}/../simulation_data/train_valid_data/Acetaminophen_orthorhombic_3_degree_dp_images_train
  targets_path_train: ${hydra:runtime.cwd}/../simulation_data/train_valid_data/Acetaminophen_orthorhombic_3_degree_targets_train
  euler_angles_path_train: ${hydra:runtime.cwd}/../simulation_data/train_valid_data/Acetaminophen_orthorhombic_3_degree_euler_angles_train.csv

  dp_images_path_valid: ${hydra:runtime.cwd}/../simulation_data/train_valid_data/Acetaminophen_orthorhombic_3_degree_dp_images_train
  targets_path_valid: ${hydra:runtime.cwd}/../simulation_data/train_valid_data/Acetaminophen_orthorhombic_3_degree_targets_train
  euler_angles_path_valid: ${hydra:runtime.cwd}/../simulation_data/train_valid_data/Acetaminophen_orthorhombic_3_degree_euler_angles_val.csv

  # class names
  class_names: ${hydra:runtime.cwd}/../simulation_data/train_valid_data/Acetaminophen_orthorhombic_3_degree_class_names.txt


simulation:
  pattern_size: 128
  pattern_sigma: 1.5
  reciprocal_radius: 0.5
  acceleration_voltage: 200.0
  max_excitation_error: 0.03
  inimum_intensity: 0.05

params:
  model: ./peakdetect.cfg # model config file
  model_name: orth_3_degree_resnet
  version: 1
  test_data_ratio: 0.05
  batch_size: 64
  precision_for_training: 16
  num_epoch: 30
  verbose: store_true
  n_cpu: 4
  iou_thres: 0.5
  conf_thres: 0.1
  nms_thres: 0.5
  seed: 0

trainer:
  max_epochs: 50
  accelerator: gpu
  devices: 1

checkpoints:
  checkpoints: ${hydra:runtime.cwd}/../checkpoints/orth_3_degree
  monitor: precision
  every_n_epochs: 5
  mode: max
  filename: "-{epoch:02d}-{precission:.2f}"


path:
  logs: ${hydra:runtime.cwd}/../lightning_logs