_target_: peakdetect.utils.dp_generator.DPGenerator

# structure
struct_path: simulation_data/Acetaminophen_orthorhombic.cif

# prepared euler_angles, dps, and targets
all_euler_angles_path: simulation_data/anglefile_Acetaminophen_orthorhombic_5_degree.txt


save_folder_path: simulation_data/test
output_name: Acetaminophen_orthorhombic_5_degree


# pattern simulation configs
pattern_size: 128
pattern_sigma: 1.5
reciprocal_radius: 0.5
acceleration_voltage: 200.0
max_excitation_error: 0.03
minimum_intensity: 0.05
