# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: lightning_logs/
  name: orth_5_degree_Resnet
  version: test
  log_graph: False
  prefix: ""
  default_hp_metric: False